version: '3'
services:
  basic-image:
    container_name: basic-image
    restart: always
    build: .
    ports:
      - 3001:3001
    links: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/


